name: GitHub Actions and Docker Scout

# Determining when this workflow runs.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# SAST scan - Bandit: Primarily for Python code
jobs:
  sast_scan:
    name: Run Bandit scout-action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Checking out the repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit ir . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-findings
          path: bandit-report.json

  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Automatic variables provided by GitHub Actions every time a workflow runs.
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/georgios-filis/hw0-26-devsecops:latest
          push: true
          no-cache: true

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview, cves
          image: ghcr.io/georgios-filis/hw0-26-devsecops:latest
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}          
          only-severities: critical, high
          sarif-file: scout-report.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-findings
          path: scout-report.sarif
